[package]
name = "migration_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
# Random stuff
anyhow = "^1.0"
dialoguer = "^0.10"
pager = "^0.16"

# Sheet stuff
csv = "^1.1"
serde = "^1.0"
serde_json = "^1.0"

# Firestore stuff
firestore-db-and-auth = "^0.6"
